import {marked} from 'marked';
import {readSnapshot,releaseCards,releaseArchive,downloadUrl,RELEASES_URL,escapeHtml as esc} from '../assets/releases-core.mjs';

import {icon,iconText} from './icons.mjs';
import {mods,categories} from '../assets/data/mods.mjs';
const download = catalog => `<a class="button primary" data-download href="${esc(downloadUrl(catalog))}">Pobierz launcher <span aria-hidden="true">↓</span></a>`;
function shell(title,content,snapshot,history=false){
 if(!history)content=content.replace(/(<section class="section" id="o-modpaku">[\s\S]*?)(<\/section>)/,'$1<div class="mod-list-action"><a class="button secondary" href="mody.html">Pełna lista modów →</a></div>$2');
 content=content.replace(/(<section class="section(?: [^"]*)?"[^>]*>)/g,'$1<span class="nordic-corner-bottom" aria-hidden="true"></span>');
 const catalog=readSnapshot(snapshot);
 content=content.replace(/<summary>(Starsze aktualizacje|Wydania launchera i beta)/g,(_,label)=>`<summary>${icon('chevron-down')} ${label}`);
 return iconText(`<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Valheim ++</title><meta name="description" content="Valheim ++: walka, budowanie i wygoda w jednej paczce modów. Pobierz launcher i sprawdź najnowsze zmiany."><meta name="theme-color" content="#0b1812"><link rel="icon" href="assets/images/valheim-emblem.png"><link rel="stylesheet" href="assets/landing.css"><link rel="stylesheet" href="assets/refinement.css"></head><body class="vh-site${history?' history':''}"><a class="skip" href="#tresc">Przejdź do treści</a>
 <header class="site-header" id="page-top"><a class="brand" href="${history?'index.html':'#page-top'}" aria-label="Valheim ++ — ${history?'strona główna':'na górę strony'}"><img src="assets/images/valheim-emblem.png" width="48" height="48" alt=""><span>VALHEIM <b>++</b></span></a><nav aria-label="Nawigacja główna"><a href="${history?'index.html':''}#o-modpaku">O paczce</a><a href="${history?'index.html':''}#launcher">Launcher</a><a href="${history?'index.html':''}#changelog">Aktualizacje</a><a href="${history?'index.html':''}#pomoc">Pomoc</a></nav>${download(catalog)}</header>
 <main id="tresc">${content}</main><footer class="site-footer"><div class="footer-overview"><a class="brand" href="${history?'index.html':'#page-top'}"><img src="assets/images/valheim-emblem.png" width="40" height="40" alt=""><span>VALHEIM <b>++</b></span></a><p>Więcej możliwości w świecie Valheim.<br>Paczka modów i launcher w jednym projekcie.</p></div><nav class="footer-links" aria-label="Linki dodatkowe"><a href="mody.html">Lista modów</a><a href="changelog.html">Historia zmian</a><a href="poradnik.html">Poradnik</a><a href="${RELEASES_URL}">GitHub ${icon('arrow-up-right')}</a></nav><a class="footer-top" href="#page-top">Na górę ${icon('arrow-up')}</a><div class="footer-bottom"><span>© ${new Date().getFullYear()} Bullet · Valheim ++</span><small>Nieoficjalny projekt społeczności Valheim.</small></div></footer>
 <script id="release-snapshot" type="application/json">${JSON.stringify(snapshot??null).replace(/</g,'\\u003c')}</script><script type="module" src="assets/releases.mjs"></script><script type="module" src="assets/landing.js"></script></body></html>`);
}
function blocks(body=''){
 const [lead,...items]=body.split(/^###\s+/m);
 return {lead:marked.parse(lead),items:items.map(item=>{const [title,...rest]=item.split('\n');return {title,html:marked.parse(rest.join('\n'))};})};
}
function galleryMarkup(gallery){
 if(!gallery.length)return '<p>Screeny launchera pojawią się tutaj wkrótce.</p>';
return `<div class="carousel" data-gallery role="region" aria-roledescription="karuzela" aria-label="Widoki launchera"><div class="carousel-viewport">${gallery.map((item,i)=>`<div class="gallery-slide" data-slide="${i}" ${i?'hidden':''} role="group" aria-roledescription="slajd" aria-label="${i+1} z ${gallery.length}"><button class="screen-button" data-screen="${i}" type="button" aria-label="Powiększ: ${esc(item.title)}"><img src="${esc(item.src)}" alt="${esc(item.alt)}" ${i?'loading="lazy"':'fetchpriority="low"'} width="960" height="640"><span class="screen-zoom" aria-hidden="true">⤢</span></button><p class="slide-caption">${esc(item.title)}</p></div>`).join('')}</div><div class="gallery-controls"><button class="gallery-arrow" data-gallery-prev aria-label="Poprzedni screen">←</button><div class="gallery-dots" aria-label="Wybierz screen">${gallery.map((item,i)=>`<button data-gallery-dot="${i}" aria-label="${esc(item.title)}" aria-pressed="${i===0}" type="button"></button>`).join('')}</div><button class="gallery-arrow" data-gallery-next aria-label="Następny screen">→</button></div></div>`;
}
export function renderLanding({source,chapters=[],snapshot,gallery=[]}){
 const catalog=readSnapshot(snapshot);
 const [intro,...raw]=source.split(/^##\s+/m);
 const sections=new Map(raw.map(s=>{const [title,...body]=s.split('\n');return [title.trim(),body.join('\n')];}));
 const paragraphs=intro.replace(/^#.*\n/,'').trim().split(/\n\s*\n/);
 const about=blocks(sections.get('O modpaku')),start=blocks(sections.get('Jak zacząć?')),help=blocks(sections.get('Pomoc'));
 return shell('Modpack i launcher',`<section class="hero"><div class="hero-inner"><p class="eyebrow">MODPACK DO VALHEIM</p><h1>${marked.parseInline(paragraphs[0]||'Valheim **++**')}</h1><div class="hero-lead">${marked.parse(paragraphs.slice(1).join('\n\n'))}</div><div class="actions">${download(catalog)}<p class="hero-version"><span data-version="modpack">Wersja ${esc(catalog?.modpack[0]?.version||'—')}</span></p></div></div></section>
 <section class="section" id="o-modpaku"><div class="section-heading"><div><p class="eyebrow">ZAWARTOŚĆ</p><h2>Co zmienia Valheim ++?</h2></div><div class="muted">${about.lead}</div></div><div class="features">${about.items.map((item,i)=>`<article class="reveal feature-illustrated"><span class="feature-number" aria-hidden="true">0${i+1}</span><span class="feature-icon">${icon(["swords","hammer","sprout","sliders-horizontal"][i%4])}</span><h3>${esc(item.title)}</h3>${item.html}<img class="feature-art" src="assets/images/feature-${['01-walka','02-budowanie','03-uprawy','04-wygodniejsza-gra'][i%4]}-v1.png" alt="" aria-hidden="true" loading="lazy" width="1536" height="1024"></article>`).join('')}</div></section>
 <section class="section launcher-section" id="launcher"><div class="reveal"><p class="eyebrow">LAUNCHER VALHEIM ++</p><h2>Instalacja, aktualizacje<br>i gra w jednym miejscu.</h2><div class="launcher-copy">${marked.parse(sections.get('Launcher')||'')}</div><a class="text-link" href="#jak-zaczac">Pobierz i zacznij →</a></div><div class="gallery reveal">${galleryMarkup(gallery)}</div></section>
 <section class="section" id="jak-zaczac"><div class="start-heading"><p class="eyebrow">NA START</p><h2>Trzy kroki do pierwszej gry.</h2><p>Pobierz launcher, wskaż Valheim i zainstaluj paczkę.</p></div><div class="steps">${start.items.map((item,i)=>`<article class="reveal"><span class="step-icon" aria-hidden="true">${icon(['download','folder-search','play'][i%3])}</span><span class="step-number">KROK 0${i+1}</span><h3>${esc(item.title)}</h3>${item.html}${i<start.items.length-1?`<span class="step-connector" aria-hidden="true">${icon('arrow-right')}</span>`:''}</article>`).join('')||start.lead}</div><div class="actions">${download(catalog)}<a class="text-link" href="${esc(chapters[0]?.file||'poradnik.html')}">Poradnik krok po kroku →</a></div></section>
 ${releaseSection(false,snapshot)}
 <section class="section" id="pomoc"><div class="section-heading"><div><p class="eyebrow">POMOC</p><h2>Pomoc pod ręką.</h2><p class="muted">Instrukcje i rozwiązania problemów.</p></div></div><div class="help-grid">${[0,1].map(column=>`<div class="help-column">${help.items.map((item,i)=>({item,i})).filter(({i})=>i%2===column).map(({item,i})=>`<details class="help-card"><summary><span class="help-topic-icon">${icon(['play','wrench','layers','shield'][i%4])}</span><span>${esc(item.title)}</span>${icon("chevron-down")}</summary>${item.html}</details>`).join('')}</div>`).join('')}</div><div class="help-actions"><a class="button primary guide-link" href="poradnik.html">${icon("book-open")} Otwórz poradnik</a></div></section>`,snapshot);
}
function releaseSection(history,snapshot){
 const entries=readSnapshot(snapshot)?.modpack||[];
 const launcherEntries=readSnapshot(snapshot)?.launcher||[];
 const secondary=history?`<details class="other-products"><summary>Wydania launchera i beta</summary><div class="release-tabs" role="tablist" aria-label="Pozostałe wydania"><button id="tab-launcher" role="tab" aria-selected="true" aria-controls="secondary-release-list" data-product="launcher">Launcher</button><button id="tab-beta" role="tab" aria-selected="false" aria-controls="secondary-release-list" data-product="beta" tabindex="-1">Beta</button></div><div id="secondary-release-list" role="tabpanel" aria-labelledby="tab-launcher">${releaseCards(launcherEntries,1)}${launcherEntries.length>1?releaseArchive(launcherEntries.slice(1)):''}</div></details>`:'';
 return `<section class="section news-section" id="changelog" data-release-area data-history="${history}"><div class="section-heading"><div><p class="eyebrow">AKTUALIZACJE MODPAKA</p><${history?'h1':'h2'}>${history?'Historia aktualizacji':'Najnowsze wydanie'}</${history?'h1':'h2'}></div></div><div id="release-list">${releaseCards(entries,1)}</div><details class="older-releases"><summary>Starsze aktualizacje</summary><div id="older-release-list">${releaseArchive(entries.slice(1))}</div></details>${secondary}<p class="caption" data-release-status role="status"></p>${history?'':'<a class="text-link" href="changelog.html">Pełna historia →</a>'}<noscript><p>Aktualne wydania sprawdzisz również na <a href="${RELEASES_URL}">GitHubie</a>.</p></noscript></section>`;
}
export function renderHistory({snapshot}){return shell('Historia aktualizacji',releaseSection(true,snapshot),snapshot,true);}
export function renderMods({snapshot}){
 const list=[...mods].sort((a,b)=>a.name.localeCompare(b.name,'pl'));
 const descriptions=['Wyposażenie, przeciwnicy i rozwój postaci na kolejnych etapach wyprawy.','Elementy konstrukcyjne, planowanie budowli i narzędzia do kształtowania terenu.','Nowe rośliny, potrawy oraz wygodniejsze prowadzenie gospodarstwa.','Porządek w ekwipunku, czytelniejszy interfejs i usprawnienia codziennej gry.','Biblioteki i narzędzia, które wspierają działanie pozostałych modów.'];
 const content=`<section class="section mods-section" id="mods-all"><div class="mods-heading"><p class="eyebrow">ZAWARTOŚĆ PACZKI</p><h1>Pełna lista modów</h1><p class="muted">Co znajdziesz w stabilnej paczce Valheim ++.</p></div><p class="mod-count" id="mod-count" role="status">${list.length} modów</p>${categories.map((category,i)=>{const group=list.filter(m=>m.category===category);return `<section class="mod-group" id="mods-${i}"><header class="mod-group-heading"><span class="mod-group-icon">${icon(['swords','hammer','sprout','sliders-horizontal','wrench'][i])}</span><div><h2>${esc(category)} <span class="mod-group-count">${group.length}</span></h2><p>${descriptions[i]}</p></div></header><div class="mod-catalog">${group.map(m=>`<article class="mod-card" data-mod-name="${esc(m.name.toLowerCase())}" data-mod-category="${esc(m.category)}"><h3>${esc(m.name.replaceAll('_',' '))}</h3><p>${esc(m.description)}</p></article>`).join('')}</div></section>`;}).join('')}<p id="mod-empty" hidden>Brak modów pasujących do wyszukiwania.</p><p class="mod-inventory-note">Zawartość stabilnej paczki · lista z 9 października 2026</p><div class="mod-list-action"><a class="button secondary" href="index.html#o-modpaku">← Wróć do paczki</a></div></section>`;
 const topbar=`<header class="site-header mods-topbar"><div class="mods-topbar-row"><a class="brand" href="index.html"><img src="assets/images/valheim-emblem.png" width="38" height="38" alt=""><span>VALHEIM <b>++</b></span></a><label class="mods-search" for="mod-search"><input id="mod-search" aria-label="Szukaj moda" type="search" placeholder="Szukaj moda…" autocomplete="off"></label></div><nav aria-label="Kategorie modów"><a href="#mods-all">Wszystkie</a>${categories.map((c,i)=>`<a href="#mods-${i}">${esc(i===2?'Uprawy':c)}</a>`).join('')}</nav></header>`;
 const cards=content.replace(/(<article class="mod-card" data-mod-name="([^"]+)"[\s\S]*?)(<\/article>)/g,(_,body,name,end)=>`${body}<button class="mod-open" type="button" data-mod="${name}" aria-label="Szczegóły moda: ${name}">${icon('maximize-2')}</button>${end}`);
 const dialog=`<dialog class="mod-dialog" aria-labelledby="mod-dialog-title"><button class="mod-dialog-close" type="button" aria-label="Zamknij opis moda">${icon('x')}</button><p class="eyebrow" id="mod-dialog-category"></p><h2 id="mod-dialog-title"></h2><p id="mod-dialog-description"></p><a class="button secondary" id="mod-dialog-source" target="_blank" rel="noopener noreferrer">Strona autora ${icon('arrow-up-right')}</a></dialog>`;
 return shell('Lista modów',cards,snapshot,true).replace(/<header class="site-header" id="page-top">[\s\S]*?<\/header>/,topbar.replace('<header class="site-header mods-topbar">','<header class="site-header mods-topbar" id="page-top">').replace('<input id="mod-search"',`${icon('search')}<input id="mod-search"`)).replace('</body>',`${dialog}<script type="module" src="assets/mods.js"></script></body>`);
}
