import {marked} from 'marked';
import {readSnapshot,releaseCards,releaseArchive,downloadUrl,RELEASES_URL,escapeHtml as esc} from '../assets/releases-core.mjs';

import {icon,iconText} from './icons.mjs';
const download = catalog => `<a class="button primary" data-download href="${esc(downloadUrl(catalog))}">Pobierz launcher <span aria-hidden="true">↓</span></a>`;
function shell(title,content,snapshot,history=false){
 const catalog=readSnapshot(snapshot);
 content=content.replace(/<summary>(Starsze aktualizacje|Wydania launchera i beta)/g,(_,label)=>`<summary>${icon('chevron-down')} ${label}`);
 return iconText(`<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Valheim ++</title><meta name="description" content="Valheim ++: walka, budowanie i wygoda w jednej paczce modów. Pobierz launcher i sprawdź najnowsze zmiany."><meta name="theme-color" content="#0b1812"><link rel="icon" href="assets/images/valheim-emblem.png"><link rel="stylesheet" href="assets/landing.css"><link rel="stylesheet" href="assets/refinement.css"></head><body class="vh-site${history?' history':''}"><a class="skip" href="#tresc">Przejdź do treści</a>
 <header class="site-header"><a class="brand" href="index.html"><img src="assets/images/valheim-emblem.png" width="48" height="48" alt=""><span>VALHEIM <b>++</b></span></a><nav aria-label="Nawigacja główna"><a href="${history?'index.html':''}#o-modpaku">O paczce</a><a href="${history?'index.html':''}#launcher">Launcher</a><a href="${history?'index.html':''}#changelog">Aktualizacje</a><a href="${history?'index.html':''}#pomoc">Pomoc</a></nav>${download(catalog)}</header>
 <main id="tresc">${content}</main><footer><a class="footer-brand" href="index.html">VALHEIM ++</a><span>© ${new Date().getFullYear()} Bullet · Valheim ++</span><nav aria-label="Linki dodatkowe"><a href="poradnik.html">Pomoc i instrukcje</a><a href="${RELEASES_URL}">GitHub</a></nav><small>Nieoficjalny projekt społeczności Valheim.</small></footer>
 <script id="release-snapshot" type="application/json">${JSON.stringify(snapshot??null).replace(/</g,'\\u003c')}</script><script type="module" src="assets/releases.mjs"></script><script type="module" src="assets/landing.js"></script></body></html>`);
}
function blocks(body=''){
 const [lead,...items]=body.split(/^###\s+/m);
 return {lead:marked.parse(lead),items:items.map(item=>{const [title,...rest]=item.split('\n');return {title,html:marked.parse(rest.join('\n'))};})};
}
function galleryMarkup(gallery){
 if(!gallery.length)return '<p>Screeny launchera pojawią się tutaj wkrótce.</p>';
return `<div class="carousel" data-gallery role="region" aria-roledescription="karuzela" aria-label="Widoki launchera"><div class="carousel-viewport">${gallery.map((item,i)=>`<div class="gallery-slide" data-slide="${i}" ${i?'hidden':''} role="group" aria-roledescription="slajd" aria-label="${i+1} z ${gallery.length}"><button class="screen-button" data-screen="${i}" type="button" aria-label="Powiększ: ${esc(item.title)}"><img src="${esc(item.src)}" alt="${esc(item.alt)}" ${i?'loading="lazy"':'fetchpriority="low"'} width="960" height="640"><span class="screen-zoom" aria-hidden="true">⤢</span></button><p class="slide-caption">${esc(item.title)}</p></div>`).join('')}</div><div class="gallery-controls"><button class="gallery-arrow" data-gallery-prev aria-label="Poprzedni screen">←</button><div class="gallery-dots" aria-label="Wybierz screen">${gallery.map((item,i)=>`<button data-gallery-dot="${i}" aria-label="${esc(item.title)}" aria-pressed="${i===0}" type="button"></button>`).join('')}</div><button class="gallery-arrow" data-gallery-next aria-label="Następny screen">→</button></div></div>`;
}
export function renderLanding({source,chapters=[],snapshot,gallery=[]}){
 const catalog=readSnapshot(snapshot);
 const [intro,...raw]=source.split(/^##\s+/m);
 const sections=new Map(raw.map(s=>{const [title,...body]=s.split('\n');return [title.trim(),body.join('\n')];}));
 const paragraphs=intro.replace(/^#.*\n/,'').trim().split(/\n\s*\n/);
 const about=blocks(sections.get('O modpaku')),start=blocks(sections.get('Jak zacząć?')),help=blocks(sections.get('Pomoc'));
 return shell('Modpack i launcher',`<section class="hero"><div class="hero-inner"><p class="eyebrow">MODPACK DO VALHEIM</p><h1>${marked.parseInline(paragraphs[0]||'Valheim **++**')}</h1><div class="hero-lead">${marked.parse(paragraphs.slice(1).join('\n\n'))}</div><div class="actions">${download(catalog)}<a class="button secondary" href="#o-modpaku">Zobacz, co jest w paczce →</a></div><a class="hero-version" href="#changelog"><span data-version="modpack">Wersja ${esc(catalog?.modpack[0]?.version||'—')}</span><span aria-hidden="true">·</span> Zobacz zmiany ↗</a></div></section>
 <section class="section" id="o-modpaku"><div class="section-heading"><div><p class="eyebrow">ZAWARTOŚĆ</p><h2>Co zmienia Valheim ++?</h2></div><div class="muted">${about.lead}</div></div><div class="features">${about.items.map((item,i)=>`<article class="reveal"><span class="feature-number" aria-hidden="true">0${i+1}</span><span class="feature-icon">${icon(["swords","hammer","sprout","sliders-horizontal"][i%4])}</span><h3>${esc(item.title)}</h3>${item.html}</article>`).join('')}</div></section>
 <section class="section launcher-section" id="launcher"><div class="reveal"><p class="eyebrow">LAUNCHER VALHEIM ++</p><h2>Instalacja, aktualizacje<br>i gra w jednym miejscu.</h2><div class="launcher-copy">${marked.parse(sections.get('Launcher')||'')}</div><a class="text-link" href="#jak-zaczac">Pobierz i zacznij →</a></div><div class="gallery reveal">${galleryMarkup(gallery)}</div></section>
 <section class="section" id="jak-zaczac"><p class="eyebrow">NA START</p><h2>Odpal launcher. Resztę zrobisz w nim.</h2><div class="steps">${start.items.map((item,i)=>`<article class="reveal"><span>0${i+1}</span><h3>${esc(item.title)}</h3>${item.html}</article>`).join('')||start.lead}</div><div class="actions">${download(catalog)}<a class="text-link" href="${esc(chapters[0]?.file||'poradnik.html')}">Potrzebujesz instrukcji ze screenami? →</a></div></section>
 ${releaseSection(false,snapshot)}
 <section class="section" id="pomoc"><div class="section-heading"><div><p class="eyebrow">POMOC</p><h2>Gdy coś nie idzie zgodnie z planem.</h2></div></div><a class="button primary guide-link" href="poradnik.html">${icon("book-open")} Szczegółowy poradnik</a><div class="help-grid">${help.items.map(item=>`<details class="help-card"><summary>${icon("chevron-down")} ${esc(item.title)}</summary>${item.html}</details>`).join('')}</div></section>`,snapshot);
}
function releaseSection(history,snapshot){
 const entries=readSnapshot(snapshot)?.modpack||[];
 const launcherEntries=readSnapshot(snapshot)?.launcher||[];
 const secondary=history?`<details class="other-products"><summary>Wydania launchera i beta</summary><div class="release-tabs" role="tablist" aria-label="Pozostałe wydania"><button id="tab-launcher" role="tab" aria-selected="true" aria-controls="secondary-release-list" data-product="launcher">Launcher</button><button id="tab-beta" role="tab" aria-selected="false" aria-controls="secondary-release-list" data-product="beta" tabindex="-1">Beta</button></div><div id="secondary-release-list" role="tabpanel" aria-labelledby="tab-launcher">${releaseCards(launcherEntries,1)}${launcherEntries.length>1?releaseArchive(launcherEntries.slice(1)):''}</div></details>`:'';
 return `<section class="section news-section" id="changelog" data-release-area data-history="${history}"><div class="section-heading"><div><p class="eyebrow">AKTUALIZACJE MODPAKA</p><${history?'h1':'h2'}>${history?'Historia aktualizacji':'Najnowsze wydanie'}</${history?'h1':'h2'}></div></div><div id="release-list">${releaseCards(entries,1)}</div><details class="older-releases"><summary>Starsze aktualizacje</summary><div id="older-release-list">${releaseArchive(entries.slice(1))}</div></details>${secondary}<p class="caption" data-release-status role="status"></p>${history?'':'<a class="text-link" href="changelog.html">Pełna historia →</a>'}<noscript><p>Aktualne wydania sprawdzisz również na <a href="${RELEASES_URL}">GitHubie</a>.</p></noscript></section>`;
}
export function renderHistory({snapshot}){return shell('Historia aktualizacji',releaseSection(true,snapshot),snapshot,true);}
